from datetime import datetime, timedelta
from typing import Dict, Any
from abc import ABC

class WorkingDataConnection(ABC):
    def __init__(self, name: str,
                        producer_type: str, 
                        producer_name: str,
                        database_type: str = None,
                        database_name: str = None,
                        query: str = None,
                        is_error: bool = False,
                        expired_time: datetime = datetime.min):

        """
        Initialize a WorkingDataConnection object.

        Args:
            name (str): Unique identifier for this data connection.
            producer_type (str): Type of the producer that this data connection belongs to.
            producer_name (str): Name of the producer that this data connection belongs to.
            database_type (str, optional): Type of the database that this data connection belongs to. Defaults to None.
            database_name (str, optional): Name of the database that this data connection belongs to. Defaults to None.
            query (str, optional): Query associated with this data connection. Defaults to None.
            is_error (bool, optional): Whether this data connection is associated with an error. Defaults to False.
            expired_time (datetime, optional): Time at which the data associated with this data connection will expire. Defaults to datetime.min.

        Attributes:
            name (str): Unique identifier for this data connection.
            producer_type (str): Type of the producer that this data connection belongs to.
            producer_name (str): Name of the producer that this data connection belongs to.
            database_type (str): Type of the database that this data connection belongs to.
            database_name (str): Name of the database that this data connection belongs to.
            query (str): Query associated with this data connection.
            is_error (bool): Whether this data connection is associated with an error.
            expired_time (datetime): Time at which the data associated with this data connection will expire.
            query_in_progress (bool): Whether a query is currently in progress for this data connection.
            is_updated (bool): Whether the data associated with this data connection has been updated.
            data_dict_match (Dict[str, Any]): Dictionary containing the data that matched the query associated with this data connection.
            data_dict_query_source (Dict[str, Any]): Dictionary containing the data that was used to generate the query associated with this data connection.
            data_dict_result (Dict[str, Any]): Dictionary containing the data that was generated by the query associated with this data connection.
        """
        self.name: str = name
        self.producer_type: str = producer_type
        self.producer_name: str = producer_name
        self.database_type: str  = database_type
        self.database_name: str  = database_name
        self.query: str = query
        self.is_error: bool = is_error

        # working data
        self.expired_time: datetime = expired_time
        self.query_in_progress: bool = False
        self.is_updated: bool = True
        self.data_dict_match: Dict[str, Any] = None
        self.data_dict_query_source: Dict[str, Any] = None
        self.data_dict_result: Dict[str, Any] = None

    def update_expired_time(self, minutes: int) -> None:
        """
        Updates the expired time for this data connection by adding the given number of minutes to the current time.

        Args:
            minutes (int): The number of minutes to add to the current time.
        """
        self.expired_time = datetime.now() + timedelta(minutes=minutes)