FROM python:3.11-slim

WORKDIR /app

COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../apps_logging_app ./apps_logging_app

WORKDIR /app/apps_logging_app

CMD ["python", "main.py"]
