FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../apps_logging_app /app/apps_logging_app

CMD ["python", "-m", "apps_logging_app.main"]

